### PR TITLE
Added Telemetry supervisor to Hello.Application children list in the guides/directory_structure.md

### PR DESCRIPTION
**Pull request by alirux**
The Telemetry supervisor was missing from the directory_structure guide.
I copied the right code from the phoenix-generated application.ex file

### CODE REVIEW

**Comment by mcrumm** [comment]
Hi @alirux! This looks good. We should add `telemetry.ex` in "The lib/hello_web directory" section, too.  wdyt?

**Comment by alirux** [comment]
You're right. Added at the end of the tree.

**Comment by mcrumm** [comment]
Thanks! ❤️

**Comment by alirux** [comment]
You are welcome! Glad to help :-)

**Comment by alirux** [comment]
Hi @mcrumm , after re-reading the entire page I found other issues, such as the missing description of the telemetry.ex file.
The last commit fixes these issues.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
