### PR TITLE
Add Render to deployment guides

### PR DESCRIPTION
**Pull request by anurag**
I work at Render. Hundreds of Phoenix users have been using our platform successfully for some time now, and there are a lot of unofficial guides:

* https://alchemist.camp/articles/elixir-releases-deployment-render
* https://www.theguild.nl/real-world-phoenix-lets-d4y/
* https://phxroad.com/devops/deploy-phoenix-app-to-render-com
* https://realworldphoenix.com/blog/2019-12-31/lets_deploy
* https://dev.to/seojeek/phoenix-deploys-with-elixir-1-9-with-systemd-no-docker-1od0

This PR adds Render as a deployment option in addition to Heroku and Gigalixir.

### CODE REVIEW

**Comment by leothorp** [comment]
Have had a smooth experience so far deploying a couple of Phoenix apps on render, IMO one of the better options out there. Glad to see it getting more visibility as an option here.

**Comment by chevinbrown** [comment]
FWIW, I've done this on both Heroku/Render + a few more over the past year, and I'm really glad to see Render added directly. Thanks, @anurag!
❤️

**Comment by anurag** [comment]
@josevalim or @chrismccord: any thoughts or suggestions for this PR?

**Comment by josevalim** [comment]
We have been discussing internally a fair rule for those guides. Ultimately, those guides have to be maintained by us, and at the moment there is nobody on the Phoenix team with experience on Render but we also want to give a shout to other platforms that support Elixir+Phoenix.

We didn't reach an agreement but my suggestion is to have a bullet list at the end of the deployment page that links to external official articles. Therefore, if there is a page on render.com that instructs developers to deploy with Phoenix, please do send a PR adding the following "footer":

```
There are also external guides for deploying Phoenix to other platforms, such as:

  * [Render](...), yada-yada short-description yada-yada
```

This will provide a space for Render and Nanobox to promote their tools without increasing the burden of the Phoenix team. Thank you!

**Comment by anurag** [comment]
@josevalim would you be open to Render maintaining their own docs like Gigalixir here: https://github.com/phoenixframework/phoenix/pull/3912 ?

**Comment by chrismccord** [comment]
I'm a gigalixir user, so it's a maintenance burden we're okay with taking on in that case. As José said, a callout to external guides would be welcome. Thanks!

**Pull request closed without merging**
