### PR TITLE
Fixes a couple of typos

### PR DESCRIPTION
**Pull request by fxn**
Just a couple of typos I saw in passing.

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by chrismccord** [comment]
Thanks @fxn, but I think the "imports" verbiage works in this case. Thanks for the PR!

**Comment by chrismccord** [comment]
Fastest person on the internet beats me again. Disregard :)

**Comment by fxn** [comment]
@chrismccord isn't "tests" the subject?

**Comment by dabaer** [comment]
@chrismccord this commit made building phoenix really flaky for some reason, I now get continuous failures whilst building: https://jenkins.strato.im/view/All/job/Phoenix/44 and https://jenkins.strato.im/view/All/job/Phoenix/45. Made all the more weird by the fact that this commit touched no code @_@

**Pull request merged**
