### PR TITLE
Docs on deploying to DigitalOcean

### PR DESCRIPTION
**Pull request by rafbgarcia**
I've started playing with Elixir/Phoenix 2 days ago and was following the guides in https://hexdocs.pm/phoenix and got stuck on deployment.

Spent a ton of time researching on how to deploy to DO, attempting pieces of possible solutions from different places, it was frustrating.

If I had seen this section in there, it'd have been much easier for me to get started.

I believe having a this doc would make Phoenix's initial experience smoother for newbies like myself.

It may not be the ideal doc, but I believe it's good enough to start with.

### CODE REVIEW

**Comment by webdeb** [comment]
Heroku has it own concept of buildpacks, so it makes sense to mention the elixir/phoenix specifics to it.

DigitalOcean has a cool & simple UI to init a vServer, though is just another hosting providing.
So I dont think the DO section makes really a lot of sense. If you follow the distillery guide, it will just work on your droplet like any other vServer.

**Comment by rafbgarcia** [comment]
Thanks for your input @webdeb.

As a newbie I didn't find distillery guides straightforward to follow through.

IMHO, it may not make sense in a technical perspective to include it there, but if you think of Phoenix as a product, you'd want your clients to get started as easy as possible, I believe.

As a dev checking Phoenix out as a possible replacement for my Rails (or whatever) app, all I want is to quickly learn some stuff about Phoenix so that I can create a simple app (Phoenix guides do a great job on that) and deploy it to a prod environment as quick as possible, so that I'm confident that I can continue to invest time on it.

If I'm not able to get a prod env working for a simple app in a reasonable amount of time, why would I switch out to Phoenix? My business needs to keep running and, as much fun as it is to try out new techs, I can't spend much time on it.

I don't mind if this PR is not merged, but I do believe it'd be beneficial for Phoenix as a product to include a guide on how to quickly deploy to vServers.

**Comment by webdeb** [comment]
> As a newbie I didn't find distillery guides straightforward to follow through.

Yeah, thats the problem, I think everybody will have that feeling when working with a completely new stack of technology. However, its the way to deploy Elixir applications in general. It very well documented, it has a lot of features to control start/stop/upgrade boot hooks and so on.

What I feel after working with elixir and phoenix, that its necessary to know the ecosystem which you are working with and it is good to know the ecosystem. The same for rails/node/php btw., you need to know the tricky parts as well.

But there is another problem with the PR. Its mentioning an unqualified source and placing it in as the source of truth for all apps hosted on DO.. I mean besides the given posts opinion based approach with edeliver (which uses distillery anyway) and quality (maybe very good), are you sure the post is up to date tomorrow? Who is responsible for keeping it up to date? Would you invest in a technology where the maintainers are linking to `some` blog post on their official guides, to tell you (the business runner) how to deploy their apps to production? that seams to be not veeery serious ;)

**Comment by rafbgarcia** [comment]
Thanks again for your inputs @webdeb.

That does make a lot of sense and I had not thought about that in that perspective. I'm really enjoying Phoenix and wanted to give other people a quicker way to get their apps working in an attempt to improve the framework and community, but I think this PR won't contribute to that.

I appreciate your time and point of view :)

**Pull request closed without merging**
