### PR TITLE
fix: phx.gen.live generator live_component/3

### PR DESCRIPTION
**Pull request by mad42**
fix for warning:
```elixir
warning: passing the @socket to live_component is no longer necessary, please remove the socket argument
```

### CODE REVIEW

**Comment by josevalim** [comment]
We also need to update the requirement of phoenix_live_view on the mix.exs of new apps. Can you please do so? Tks!

**Comment by mad42** [comment]
@josevalim done!

**Comment by mad42** [comment]
Is the CI failing because of Fastly being down ?
https://status.fastly.com/

**Comment by josevalim** [comment]
@mad42 I believe you need to run `mix deps.get` in the integration_test directory. :)

**Comment by mad42** [comment]
> @mad42 I believe you need to run `mix deps.get` in the integration_test directory. :)

I'll do it once hex.pm will come back to life 😄

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
