### PR TITLE
fix phx.new generated generators config with --binary-id

### LINKED ISSUE #2155: mix phx.new generate wrong config for generators
image

### PR DESCRIPTION
**Pull request by AlexanderChen1989**
image

web_app's type is string

fix #2155

### CODE REVIEW

**Comment by chrismccord** [comment]
Thanks! Can you add a test-case?

**Comment by AlexanderChen1989** [comment]
OK, I will add a test-case

**Comment by AlexanderChen1989** [comment]
test-case added

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
