### PR TITLE
fix code order. follows code from web module order

### PR DESCRIPTION
**Pull request by yordis**
This follows the order from here https://github.com/phoenixframework/phoenix/blob/cm-phx-gen-next/installer/templates/phx_umbrella/apps/app_name_web/mix.exs#L23

### CODE REVIEW

**Comment by josevalim** [comment]
We are getting rid of the :applications key so no need for ordering, thank you!

**Comment by yordis** [comment]
@josevalim sorry I am confused on something, we are getting rid of `:applications` but what happen with `:extra_applications`?

Which it's weird that I have this `extra_applications: [:logger]]` in every single OTP app 😄

**Comment by chenxsan** [comment]
@yordis Guess you could check it here http://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/#application-inference

**Comment by yordis** [comment]
@chenxsan what should I check there?

**Pull request closed without merging**
