### PR TITLE
Add execute permission to server in a container

### PR DESCRIPTION
**Pull request by N-0x90**
Generate the image from Azure leave the /app/bin/server without execute flag.
Its needed to place this explicit to make it work correctly.

### CODE REVIEW

**Comment by chrismccord** [comment]
It's not clear why a build on azure would result in the server not being executable. `chmod +x` is what we would want if this is required, but it would be nice to know more about why this isn't working out of the box. Thanks!

**Comment by N-0x90** [comment]
I don't make a full in deep analyses about this, but this is what I see...
Making a total new project and prepare the deploy and pipeline... then deploy it over web app and get

message: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"/app/bin/server\": permission denied: unknown"

Its a strange because if i make the same build from my pc all works flawless, but when the pipeline execute the copied files inside the image only have 

-rwxr-xr-x 1 nobody root 5308 Apr 14 06:04 project
-rwxr-xr-x 1 nobody root 6461 Apr 14 06:04 project.bat
-rw-r--r-- 1 nobody root   83 Apr 14 06:04 migrate
-rw-r--r-- 1 nobody root   49 Apr 14 06:04 migrate.bat
**-rw-r--r-- 1 nobody root   77 Apr 14 06:04 server**
-rw-r--r-- 1 nobody root   46 Apr 14 06:04 server.bat

then if add +x explicit all works flawless again...

**Comment by dvic** [comment]
And have you checked the file itself on your computer? Does it have the execute flag?

**Comment by N-0x90** [comment]
on my pc "windows" when i see the generated image it have 755 permisions...

**Comment by chrismccord** [comment]
Closing this until we have more insight on if this is really required for azure. Thanks!

**Pull request closed without merging**
