### PR TITLE
Use Phoenix and Phoenix.HTML through npm packages

### PR DESCRIPTION
**Pull request by josevalim**
Pending:

* [x] fix phoenix.js for browser
* [x] limit copying of phoenix files to npm_modules
* [x] test umbrellas
* [x] fix phoenix_live_reload in backwards compatible fashion and release

### CODE REVIEW

**Comment by chrismccord** [comment]
phoenix.js fixed for browser and push to this PR. I think that knocks out all outstanding on this one

**Comment by paulmillr** [comment]
nice shit!

**Comment by chrismccord** [comment]
@paulmillr thanks again for all your help! The brunch npm integration is super nice. <3 <3 <3

**Comment by stevedomin** [comment]
This is way nicer! :heart:

**Comment by imranismail** [comment]
:+1:  :+1:  :+1:  :+1:

**Pull request merged**
