### PR TITLE
Fix spacing between generated Edit and Back links.

### PR DESCRIPTION
**Pull request by mattneel**
Just some simple span tags around it fixes it on the 3.x and 4.x CDN versions of Bootstrap I've tested.

### CODE REVIEW

**Comment by josevalim** [comment]
@mattneel thank you! can you please do so for all relevants views in here? https://github.com/mattneel/phoenix/tree/fb29de14ce66bef128bae28244bed4915cf891c4/priv/templates/phoenix.gen.html

**Comment by mattneel** [comment]
Done. Weird Travis-CI fail on OTP 19 though.

**Comment by josevalim** [comment]
Thank you! Btw, quick question that I realized just now. Wouldn't it be semantically better to use `<p>` instead of `<span>`?

**Comment by mattneel** [comment]
<p> Will cause a linebreak, which I don't think is the intention. Wrapping with span applies the Bootstrap padding correctly.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
