### PR TITLE
Optimize extracted css

### PR DESCRIPTION
**Pull request by chenxsan**
Should fix https://github.com/phoenixframework/phoenix/issues/2809

### CODE REVIEW

**Comment by chenxsan** [comment]
Btw, there's only one `webpack.config.js` file now, I would propose adding two of them, one for `developement`, one for `production`. Since there's no need to extract css when we are developing, it could [speed up our webpack build performance](https://webpack.js.org/guides/build-performance/#avoid-production-specific-tooling).

**Comment by josevalim** [comment]
We use CSS changes in our live reloader. Without it we would always refresh
the whole page.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Don’t we have another way to say we only want to minimize in production
without having separate files?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Thanks @chenxsan! @Gazler provided a PR though that is conditional so I merged that instead because that's closer to what you want. :heart:

**Pull request closed without merging**
