### PR TITLE
highlight HEEx and EEx using the new makeup lexers

### PR DESCRIPTION
**Pull request by tmbb**
Highlight EEx and HEEx from the guides with the new Makeup lexers. Example here (from the guides): https://tmbb.github.io/phoenix/views.html

Merging this is pretty safe as the new code is only used to generate the docs.

### CODE REVIEW

**Comment by milmazz** [comment]
@tmbb Did you notice this?

Screen Shot 2022-03-08 at 21 55 40

It happens in a couple of places.

This is current version from HexDocs.

Screen Shot 2022-03-08 at 21 56 09

**Comment by tmbb** [comment]
No, I didn't! I'm not sure what's causing it. I'll look into it (I'm away from my computer now).

**Comment by tmbb** [comment]
Fixed

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
