### PR TITLE
Remove extra flash

### PR DESCRIPTION
**Pull request by jeregrine**
The app and the root both have the same flash component. 

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/components/layouts/root.html.heex#L15-L27 

And

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/components/layouts/app.html.heex#L40-L52

I am removing from the root.

### CODE REVIEW

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by shamanime** [comment]
I noticed this and opened https://github.com/phoenixframework/phoenix/issues/5011.

The only issue is that the phx.gen.auth generators redirects to "/" with a flash message when it fails and since it doesn't use the app layout now it won´t displays the flash.

Thoughts @chrismccord?

Perhaps the flash could be moved to the template instead for this case?

**Comment by leandrocp** [comment]
For eg this flash won't be displayed:

https://github.com/phoenixframework/phoenix/blob/16c3e9e818be9122ea6b666f6beecf11c4548fd1/priv/templates/phx.gen.auth/reset_password_controller_test.exs#L118-L119

Due to https://github.com/phoenixframework/phoenix/blob/16c3e9e818be9122ea6b666f6beecf11c4548fd1/installer/templates/phx_web/controllers/page_controller.ex#L4

**Comment by chrismccord** [comment]
We can put flash in the `home.html.heex` template or leave it out. The landing page in the app is considered "throw away" as you necessarily replace it in your own application. The controller does `plug :put_layout, false when action in [:home]`

**Pull request merged**
