### PR TITLE
Adds gettext() to phoenix.gen.html

### PR DESCRIPTION
**Pull request by wintermeyer**
This pull request is an attempt to make i18n a first class citizen when using `phoenix.gen.html`.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you but I am a strong -1. It makes Phoenix generators more complex
for everyone who does not care about gettext, which I believe to be the
majority of users.

On Monday, May 16, 2016, Stefan Wintermeyer <notifications@github.com>
wrote:

> This pull request is an attempt to make i18n a first class citizen when
> using phoenix.gen.html.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/phoenixframework/phoenix/pull/1705
> Commit Summary
>
>    - Adds gettext() to phoenix.gen.html
>
> File Changes
>
>    - *M* priv/templates/phoenix.gen.html/controller.ex
>    <https://github.com/phoenixframework/phoenix/pull/1705/files#diff-0>
>    (6)
>    - *M* priv/templates/phoenix.gen.html/edit.html.eex
>    <https://github.com/phoenixframework/phoenix/pull/1705/files#diff-1>
>    (4)
>    - *M* priv/templates/phoenix.gen.html/form.html.eex
>    <https://github.com/phoenixframework/phoenix/pull/1705/files#diff-2>
>    (4)
>    - *M* priv/templates/phoenix.gen.html/index.html.eex
>    <https://github.com/phoenixframework/phoenix/pull/1705/files#diff-3>
>    (12)
>    - *M* priv/templates/phoenix.gen.html/new.html.eex
>    <https://github.com/phoenixframework/phoenix/pull/1705/files#diff-4>
>    (4)
>    - *M* priv/templates/phoenix.gen.html/show.html.eex
>    <https://github.com/phoenixframework/phoenix/pull/1705/files#diff-5>
>    (8)
>
> Patch Links:
>
>    - https://github.com/phoenixframework/phoenix/pull/1705.patch
>    - https://github.com/phoenixframework/phoenix/pull/1705.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/pull/1705>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by wintermeyer** [comment]
Are you saying that the majority of users don't do any i18n or that they don't use gettext?

**Comment by josevalim** [comment]
They Don't do any i18n. The goals for gettext in Phoenix is to provide the
minimum for users to get started without getting in the way of those who do
not need i18n.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
random opinion: perhaps this could be configured and disabled by default? People who don't use gettext will see no difference, but people who do will benefit from it. This would put more maintenance burden on the core team though. Another option is to start with a plugin and based on user feedback re-evaluate.

**Comment by josevalim** [comment]
@wojtekmach today generators already allow you to customize the generated templates, so i would recommend folks to use this feature instead. Specially because it is also unlikely developers will be using Phoenix' default template to build their applications.

**Pull request closed without merging**
