### PR TITLE
Handle 403 status in javascript

### PR DESCRIPTION
**Pull request by jakgajtk**
Fix connected to this issue - https://github.com/phoenixframework/phoenix/issues/3621

### CODE REVIEW

**Comment by jakgajtk** [comment]
@chrismccord It should be ready to merge now, please let me know in case something's wrong here.

**Comment by indrekj** [comment]
The PR probably could use a rebase/squash, but would like to get this merged as well.

**Comment by sviik** [comment]
Would it make sense to pass some context to the `onerror` callback? E.g. the response from backend, containing status code.

**Comment by jakgajtk** [comment]
@indrekj Why? Aren't all commits getting squashed anyway here? If not, I will rebase it and put all changes in one commit.

**Comment by jakgajtk** [comment]
@sviik I did it similar to case for status `500` just below this one - `onerror` is called without arguments there as well.

**Comment by jakgajtk** [comment]
@snewcomer Awesome! 😄

**Comment by jakgajtk** [comment]
@snewcomer do you need anything else here from me (rebase etc.)?

**Comment by snewcomer** [comment]
@jakgajtk Yep!  Just one thing - back out the `/priv` && `/installer` additions.  Thank you!

**Comment by jakgajtk** [comment]
@snewcomer Done! I thought I was supposed to commit those builded files as well.

**Pull request merged**
