### PR TITLE
Add SourceMaps to minified JS

### PR DESCRIPTION
**Pull request by maennchen**
As discussed in https://groups.google.com/g/phoenix-core/c/Dk2AbXVnzeg

When running `npm run build`, this will:

* Add a comment to `priv/static/phoenix.js` pointing to the sourcemap
* Add a new file `priv/static/phoenix.js.map`

I have verified that when using webpack in your application, it will incorporate this sourcemap and therefore create better error stacktraces.

### CODE REVIEW

**Comment by gcauchon** [comment]
I'm not a Webpack expert, but should we also adapt the`webpack.config.js` template to include a sourcemap in the production bundle too?

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_assets/webpack.config.js#L27

```js
    devtool: devMode ? 'eval-cheap-module-source-map' : 'source-map',
```

**Comment by maennchen** [comment]
@gcauchon I don't think so. The reason is that this is a decision that the user of the framework should make:

* Open Source Applications: Shoud probably have it
* Closed Source Applications: Most companies do not want to expose their unminified JS. If using Sentry for example a `hidden-source-map` can be used and uploaded instead.

**Comment by rktjmp** [comment]
Same: https://github.com/phoenixframework/phoenix/pull/4265

**Comment by maennchen** [comment]
@rktjmp I don't think so. The linked PR is for the phoenix generator. This PR only looks at the JS packaged with phoenix.

**Comment by maennchen** [comment]
Rebased to current `master`

**Comment by maennchen** [comment]
Rebased to current `master`

**Comment by maennchen** [comment]
Amended compiled JS & Source Maps as discussed with @bcardarella

**Comment by bcardarella** [comment]
I believe if you add to this block https://github.com/phoenixframework/phoenix/blob/dcc93986fdc13120c79b0ae49771a8692df4e533/installer/lib/phx_new/single.ex#L89-L97 to ensure the new sourcemap file is being copied in for `--no-webpack` projects this PR should be ready to merge.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
