### PR TITLE
Fix link to adding pages

### PR DESCRIPTION
**Pull request by laurentqro**
Fixes the link to the Adding Pages section on the Up and Running section.

### CODE REVIEW

**Comment by chrismccord** [comment]
Can you update the link to point directly to the hex docs url? Thanks!

**Comment by laurentqro** [comment]
@chrismccord done 👌

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by hvnsweeting** [comment]
I got the error that this PR fixed, when would the fix deploy? it is 11 days ago

**Comment by chrismccord** [comment]
Guides are generally only published when we do a release, so they will appear on hexdocs when 1.4 is released

**Comment by soteras** [comment]
#3020

**Pull request merged**
