### PR TITLE
updated phx.gen.json.ex file for not to generate extra changeset_json.ex

### PR DESCRIPTION
**Pull request by varshneydevansh**
**Issue >** phx.gen.json with namespace (--web) creates duplicate changeset_json.ex #5475

This PR adds a change to the file `phx.gen.json.ex`  to prevent the problem of redundant `changeset_json.ex` file generation in namespaces.

The following code line is changed to:
```elixir
{:new_eex, "changeset_json.ex", Path.join([web, "controllers/changeset_json.ex"])},
```

### CODE REVIEW

**Comment by varshneydevansh** [comment]
Hi! Po,

https://github.com/phoenixframework/phoenix/issues/5475#issuecomment-1591814510

this was the result of the test after running the mix test -
```
Finished in 87.6 seconds (6.0s async, 81.5s sync)
11 doctests, 883 tests, 64 failures

Randomized with seed 543721
```

**Comment by varshneydevansh** [comment]
https://gist.github.com/varshneydevansh/395a73cdd10885520d05f5ffdbacb213

This is the result of the mix test which I ran just now after syncing my current branch.

```
.....................
Finished in 69.3 seconds (5.9s async, 63.3s sync)
11 doctests, 886 tests, 64 failures

Randomized with seed 603368
```

**Comment by princemaple** [comment]
They don't look very relevant to your change. I hope when CI is approved, they show something different.

My guess is that your git checks out code and changed line ending to windows line ending. You might want to change your git config (`your_user_path/.gitconfig`) to check out as-is and commit as-is, i.e. auto-crlf = false.

```ini
[core]
        autocrlf = false
```

**Comment by varshneydevansh** [comment]
image

I did these two before executing the above test (refer to above image)



I again ran the test with -
```
git checkout main
git push
git pull upstream main
```
then I ran `mix text`

Refer to the below image.

image

Am I making a mistake? Please guide me if I am missing out anything.

These were the commands which I executed in the terminal.
image

**Comment by varshneydevansh** [comment]
Hi @chrismccord, can you review this and guide me with the failing test cases?

Regards.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by varshneydevansh** [comment]
It's my first-ever PR, and I am so happy because of you, Chris, I am now able to contribute to more projects. ❤️

**Pull request merged**
