### PR TITLE
Improve Mix.Phoenix.Schema array error message

### PR DESCRIPTION
**Pull request by gavlak**
This PR solves #2257 

When you generate schema with key of type array, but without the type of the array, the following error message is now raised:

```
$ mix phx.gen.schema Post posts settings:array
** (Mix) Phoenix generators expect the type of the array to be given.
For example:

    mix phx.gen.schema Post posts settings:array:string
```

### CODE REVIEW

**Comment by almielczarek** [comment]
Also, I may be missing something, but I do not think that is the place to add the check for an array. The way it looks to me is that every time anyone passes the type :array to the generator it will match on your new function clause and raise.

I don't mean to be annoying, but I started working on this and didn't have an internet connection to see that you did too, and I found that doing the check by `validate_attr` caused mix to raise only when it should.

**Comment by gavlak** [comment]
I messed that up and noticed I'm quite a few commits behind. I'll fix that.

As for the build failing. When I tested it on my machine it passed just fine, but `Phoenix.Integration.WebSocketTest` seems to fail sometimes. That's the only failed test on Travis too.

I also saw your other comment and I think you're right. Pattern matching `validate_attr!` looks much nicer, clearer and makes more sense than checking the value in `schema_type`. I'll change that too.

**Comment by almielczarek** [comment]
I deleted that comment because I found the function pipeline was raising before hitting `validate_attrs!` causing the validation to never be run. So I think that if you're not changing anything else here you have to put the check where you did to make sure it gets run.

And once again, I could be missing something, but I still think it should be checked by `validate_attrs!`, but then we need to either change the order that functions are called here or stop raising by `schema_type` and instead calling `validate_attrs` where it would normally raise so the array check happens first. Either way if you pass an unsupported type it'll raise saying it is an unknown type.

If that wasn't clear I'll try to rephrase it.

**Comment by chrismccord** [comment]
This looks good. Can you add a test case? Thanks!

**Comment by gavlak** [comment]
Done.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
