### PR TITLE
Update bootstrap version to latest (3.3.5)

### PR DESCRIPTION
**Pull request by wiserfirst**
Just noticed the bootstrap version in a newly generated phoenix app is still 3.1.1, which was released early last year. I'm not sure if there is a particular reason why this has not been updated, but since all 3.x versions of bootstrap are supposed to be compatible, updating to 3.3.5 shouldn't break anything.

### CODE REVIEW

**Comment by chrismccord** [comment]
Have you verified that things look appropriate?

**Comment by wiserfirst** [comment]
@chrismccord I built and installed the installer ez package, and generated a new test app with it. The home page looks exactly the same as before on Chrome, Firefox and Safari.

**Comment by chrismccord** [comment]
<3 <3 <3

**Comment by wiserfirst** [comment]
:tada:

**Pull request merged**
