### PR TITLE
deployment guide: Application.load -> ensure_all_started

### PR DESCRIPTION
**Pull request by djthread**
I loved to see this documentation, but I ran into a snag. My postgrex configuration has `ssl: true`, so the `:ssl` app is required for the connection. When I followed this guide, I got:

```
** (EXIT from #PID<0.165.0>) an exception was raised:
    ** (RuntimeError) SSL connection can not be established because `:ssl` application is not started,
you can add it to `extra_application` in your `mix.exs`:

  def application do
    [extra_applications: [:ssl]]
  end

        (postgrex) lib/postgrex.ex:538: Postgrex.ensure_deps_started!/1
        (postgrex) lib/postgrex.ex:480: Postgrex.child_spec/1
        (ecto_sql) lib/ecto/adapters/sql.ex:462: Ecto.Adapters.SQL.init/3
        (ecto) lib/ecto/repo/supervisor.ex:162: Ecto.Repo.Supervisor.init/1
        (stdlib) supervisor.erl:295: :supervisor.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

In the #elixir-lang channel, _gamache_ helped me with the solution: `Application.ensure_all_started/1` is needed. Perhaps we should use this in the docs so others don't get bit by the same issue?

Thanks!!!

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks for the PR! I changed the fix in favor of an extra paragraph but, even though, I am a bit worried about advising people to start the whole app due to other side effects. I would love to see what others think.

**Comment by chrismccord** [comment]
I think even though the paragraph cautions about starting the app, that folks may miss it or may not realize the consequences. Perhaps a happy path is to show conditional starting of `server: true` so folks know how to avoid the most obvious foot gun?

**Comment by josevalim** [comment]
@chrismccord how does it look now?

**Comment by chrismccord** [comment]
perfect ❤️❤️❤️🐥🔥

**Pull request merged**
