### PR TITLE
Phoenix.js: Add support for AMD/RequireJS.

### PR DESCRIPTION
**Pull request by Skinney**

### CODE REVIEW

**Comment by chrismccord** [comment]
Can you confirm that this works as before where Phoenix.* is exposed on the global namespace? I see it in the code, but have you tested it yourself?

**Comment by chrismccord** [comment]
And thank you! :)

**Comment by Skinney** [comment]
I was a bit to quick. It created a window.Phoenix variable, but it was undefined. This new commit fixes that.

**Comment by Skinney** [comment]
Anything else I need to fix?

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
