### PR TITLE
determine duplicate channels using Array.prototype.filter until IE11 de-supported

### LINKED ISSUE #3965: phoenix.js error in IE11
### Environment

* Phoenix version: 1.5.4

### Expected behavior
Works fine with IE11.

### Actual behavior
IE11 throws an exception: “Object doesn't support property or method 'find'”

Commit that has introduced that exception: https://github.com/phoenixframework/phoenix/commit/8b0d39058ca19a3a55249f6392eb940e22047380

The line is 
```js
let dupChannel = this.channels.find(c => c.topic === topic && (c.isJoined() || c.isJoining()))
```

### PR DESCRIPTION
**Pull request by levistovall**
…herwise channels.find
fixes #3965

### CODE REVIEW

**Comment by ivanovv** [comment]
@levistovall why don't we fallback to safe version without checking IE version, and put a comment to rewrite it once we drop support for IE11?

**Comment by levistovall** [comment]
@ivanovv so you'd rather handle the case of any browser with Array.prototype.filter for now and then potentially change it back to this.channel.find when IE11 support is removed? That makes sense to me; I just wanted to make sure I understood you.

**Comment by ivanovv** [comment]
@levistovall yes, exactly that

**Comment by levistovall** [comment]
@ivanovv does it look okay to you now?

**Comment by ivanovv** [comment]
@levistovall it sure does. The problem is – framework authors ignore this PR and the issue it fixes

@josevalim @chrismccord can you chime in, guys? Do we still support IE11?

**Comment by chrismccord** [comment]
We are no longer officially supporting IE11 within phoenix.js source itself. Microsoft has announced end-of-life for the browser for less than a year from now, and the market share is half a percent or less. For folks requiring IE11 support, they can add the necessary polyfills to their own asset builder and achieve IE11 support. Thanks!

**Pull request closed without merging**
