### PR TITLE
mix.exs template: apps and deps on individual lines

### PR DESCRIPTION
**Pull request by henrik**
How do you feel about this style change?

It arguably reads cleaner since the first and last line is no longer special.

It has some additional minor benefits: cleaner diffs, lets you more easily move lines around (without accidentally introducing syntax errors thanks to the trailing comma on the last line), won't unnecessarily shift the git blame of the previous line.

It does make this file a few lines longer due to the additional line breaks – I don't mind but maybe someone else does?

### CODE REVIEW

**Comment by chrismccord** [comment]
We match the convention of Elixir and mix generators so my preference is to follow Elixir. I think this is a fine convention if you prefer it. Thanks!

**Comment by henrik** [comment]
@chrismccord Alright, if this is an Elixir convention I can see that you'd want to follow it. Easy enough to change if you feel there are benefits to doing it differently. Thanks for the feedback!

**Comment by henrik** [comment]
@josevalim @ericmj Since Elixir/Mix are still young and plastic, how do you feel about changing this convention in Mix generators? :) I'd feel remiss not to ask since I think it has some benefits.

**Comment by josevalim** [comment]
As one would expect, I actually prefer the current style.  :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by henrik** [comment]
@josevalim It was worth a shot ;) Thank you for taking the time!

**Pull request closed without merging**
