### PR TITLE
Support graceful close

### PR DESCRIPTION
**Pull request by fishcakez**

### CODE REVIEW

**Comment by josevalim** [comment]
Beautiful! Maybe we should make it part of plug and then change Phoenix to
use it?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
I didn't make this PR to plug because there would be edge cases where it could break when starting cowboy as part of the ranch supervision tree.

**Comment by fishcakez** [comment]
Also note that can not guarantee it will work in future versions of ranch/cowboy, i.e. cowboy 2.

**Comment by josevalim** [comment]
@fishcakez so should we add even add it to Phoenix? :)

**Comment by fishcakez** [comment]
@josevalim I don't know :smile:, last time this came up was https://github.com/phoenixframework/phoenix/issues/1742. The method here is reliable and would always occur before exit signals so no need to trap. However both rely equally on ranch listener sub tree, which was not discussed.

**Comment by fishcakez** [comment]
I think this is too fragile in the longer term for the core maintainers to guarantee continuous support. I think it would better to contribute this to ranch 1.2/cowboy 2.0 and await plug support for that. Certainly it would be nice to see some contribution in that direction. I will leave the branch on my github so it can be cherry-pick'ed by anyone in need of the feature - there will be no support for it from me.

**Pull request closed without merging**
