### PR TITLE
Add an overview and diagram to the 'Moving Parts' section

### PR DESCRIPTION
**Pull request by nathanl**
I had a hard time following the "Moving Parts" section initially, and thought a diagram could clarify how things work.

I made this diagram using [Monodraw](https://monodraw.helftone.com/). The Monodraw file is much easier to edit and update than the exported text, but weighs a few KB. If you like this diagram, you can decide whether you also want the Monodraw file checked in.

### CODE REVIEW

**Comment by nathanl** [comment]
This is purely a documentation change; the test failures are unrelated.

**Comment by nathanl** [comment]
> I'm not wild about including a proprietary (mac only too!) format in the repository 

Yep, totally understand. I'll hang on to the file in case changes are needed, but worst case, it wouldn't be terribly hard to recreate this using another tool.

**Comment by chrismccord** [comment]
Beautiful! Thanks you! This has definitely been an area of confusion for folks so having the new text an d diagram will definitely help. Since we're just using the ascii output from Monodraw, I'm fine adding it as is. If we need to tweak it in the future we can recreate with something else, but I don't think it will change too often. ❤️❤️❤️❤️❤️❤️🐥🔥

**Comment by nathanl** [comment]
🎆 🎆

**Pull request merged**
