### PR TITLE
interface npm scripts 

### PR DESCRIPTION
**Pull request by c4710n**
`scripts` section of `package.json` is a good place to provide commands which are used by Phoenix.

If we abstract the long commands into short npm scripts, we will:
+ have a unified interface to call node.js related commands.
+ avoid the long commands(such as `node node_modules/webpack/bin/webpack.js --mode development`) spreading in the code

And, there are two more advantage:
+ The developers who want to implement his own `assets` dir will have a better view on what they should implement - `just provides necessary NPM scripts, no need to touch the Phoenix code`.
+ When Phoenix Team decide to upgrade to Webpack 5, just update the npm scripts, there's nothing need to do with the Elixir code.

### CODE REVIEW

**Comment by josevalim** [comment]
This would be our preferred approach but every time we made this change people reported issues, especially on OSes like Windows. So if someone can try this out on a Windows machine (under WSL, mingw, cygwin, etc), then we can merge it, otherwise it is probably best to leave it as is. :(

**Comment by c4710n** [comment]
I will try this out on a Windows machine like you said.

**Comment by c4710n** [comment]
## Running modified version `phx.new`

```
$ git clone -b adjust-assets https://github.com/c4710n/phoenix.git
$ cd phoenix/installer
$ mix deps.get
$ mix compile
$ mix phx.new /tmp/demo
```

## WSL

- Sub System: Ubuntu 20.04.2 LTS
- Elixir: 1.11.2 (Following the installation at [here](https://elixir-lang.org/install.html#gnulinux))
- Node.js: 10.19.0 (installed by `sudo apt-get install nodejs`)
- npm: 6.14.4 (installed by `sudo apt-get install npm`)

WSL works like a generic Linux box, no issue found.

## web installer

- Git: 2.3.1 (installed by [installer](https://git-scm.com/download/win) provided by https://git-scm.com)
- Elixir: 1.11.2 (installed by [installer](https://github.com/elixir-lang/elixir-windows-setup/releases/download/v2.1/elixir-websetup.exe) by Elixir team)
- Node.js: 14.16.1 (installed by [installer](https://nodejs.org/en/download/) provided by Node.js team)
- npm: 6.14.2 (included in above installer)

After the installation, `elixir` `mix` `npm` can be found in the `PATH` environment variable.

But, error occured, just like #1218.

> I think that's what you said above.

After serveral hours, I think I can't fix this problem.

## mingw / cygwin

Ignore them for now.

The above problem has not been solved, and there is no point in solving this problem. ;(

## Conclusion

Currently, there's no one perfect solution. I will give up this PR.

**Comment by josevalim** [comment]
Thanks for checking, it is very appreciated! <3

**Pull request closed without merging**
