### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by m-allanson**

### CODE REVIEW

**Comment by Gazler** [comment]
Thanks <3

**Comment by c4710n** [comment]
This commit should be reverted.

The modified sentence is wrong. There is no verb in the modified sentence: 
```
The modules responsible for rendering our views.   X wrong
```

**Comment by m-allanson** [comment]
You are correct, my mistake. I tripped up reading that sentence. How do you feel about clarifying it like this?

```diff
+ The modules responsible for rendering are called views.
- The modules responsible for rendering are views.
```

**Comment by Gazler** [comment]
@m-allanson +1 for the correction, please open a PR. Thanks for raising this @c4710n

**Pull request merged**
