### PR TITLE
Updating mix task documentation to prefer mix phx.new

### PR DESCRIPTION
**Pull request by IRog**
There could have been a reason for why this was left with the old style, if so, apologies...

### CODE REVIEW

**Comment by nekath** [comment]
@josevalim I think we should also change phoenix.new to phx.new in these lines:
https://github.com/phoenixframework/phoenix/pull/2487/files#diff-f9aa62c677a08d62b01364406049fe21L46
https://github.com/phoenixframework/phoenix/pull/2487/files#diff-f9aa62c677a08d62b01364406049fe21L48

**Comment by jeregrine** [comment]
@IRog Can you please update the lines that @nekath mentioned. Thanks!

**Comment by IRog** [comment]
Will do when I get home. Thanks!

**Comment by IRog** [comment]
I updated the lines and a few more. (let me know, if I could do anything else). @jeregrine

**Comment by jeregrine** [comment]
Thank you!! 💟

**Pull request merged**
