### PR TITLE
Add built-in mechanism for rendering nested layouts

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by juliogoldbach** [comment]
Hi @josevalim, I see from this PR changes that passing a struct as `assigns` for render functions in lib/phoenix/view.ex is not possible anymore since Map.new just accepts variables with Enumerable protocol. Was this the expected result? I dont see anything related to this in v1.5 changelog.

**Comment by josevalim** [comment]
It was never really expected to receive structs, so this was intentional but I didn’t think structs were actually being given. Probably worth a CHANGELOG entry.

**Comment by juliogoldbach** [comment]
@josevalim I added a PR to update the v1.5 CHANGELOG. Thanks for the fast answer

**Pull request merged**
