### PR TITLE
Set hostname to localhost by default for dev and test

### LINKED ISSUE #1173: Set hostname to localhost by default
See: http://iamvery.com/2015/08/29/phoenix-database-config.html

### PR DESCRIPTION
**Pull request by stevedomin**
Fixes #1173 

@josevalim I assumed this was only needed in dev and test but not for prod. Let me know if that's not the case

### CODE REVIEW

**Comment by josevalim** [comment]
Isn't the configuraiton "hostname" instead of only "host"?

**Comment by stevedomin** [comment]
:( :( :( so sorry I missed that, my bad

**Comment by chrismccord** [comment]
thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
