### PR TITLE
Update testing guides for 1.3

### PR DESCRIPTION
**Pull request by bryanstearns**
This fixes phoenixframework/phoenix_guides#721 and completes the remaining work mentioned in phoenixframework/phoenix_guides#707, updating the testing guides for Phoenix 1.3. Some of this was just mix task renaming (`phoenix.xxx` -> `phx.xxx`), but there was a lot of rework to the (former) testing_models guide.

Details:
- Tweaked the Ecto guide to fix a phx.gen.schema command, adding the context module name
- Removed the empty testing/testing_views.md file
- In testing.md, updated the generated directory structure, output examples, and ecto guide name
- In testing_channels, updated the mix task name and removed mention of ChannelCase importing query stuff (it doesn't)
- Renamed testing_models to testing_schemas, and updated: the generators no longer create a schema test (so I have the reader create it), and lots of the test output needed to be updated.
- Added a "work in progress" note to the Testing overview, since maybe we ought to add more coverage of context testing? (I started to document the generated context tests, but what I came up with didn't seem useful, and I wasn't sure what strategies to convey about adding more context tests.)
- Updated the controller testing guide with Phoenix 1.3-ish module names, paths, etc.

### CODE REVIEW

**Comment by jeregrine** [comment]
@bryanstearns Looks good so far! I look forward to the controller test.

**Comment by bryanstearns** [comment]
@jeregrine Sorry for the noise - after I added the controller-testing update just now, GitHub presented a conflict with master; I edited it using GitHub's UI, and GitHub helpfully recorded it as a merge from master. I thought this was icky, so I rebased my branch and force-pushed to get rid of the merge commit.

**Comment by jeregrine** [comment]
@bryanstearns Thank you so much!!!

**Comment by jmarca** [comment]
Still some issues to my reading.  Is it okay for me to edit this guide some more?

**Comment by Gazler** [comment]
@bryanstearns Do you have any additional changes left to be merged here? If not, I'd say go ahead @jmarca

**Comment by jeregrine** [comment]
I say go for it!

**Comment by jmarca** [comment]
To be clear, I'm just tweaking the testing controllers guide.  I guess the original PR here covers a lot more than that, but I'm not that ambitious right now. Also it seems the overall project name switched from HelloPhoenix in the original guide to just Hello.  I'll correct my stuff and switch to Hello as well.

**Comment by bryanstearns** [comment]
@jmarca Go for it!

**Comment by jmarca** [comment]
Okay.

Can I ask questions here?  First question, I like to use `setup/1` to pre-run things like loading the DB with users.  I wanted to put that into the guide because it is something I looked for when starting work in Elixir/Phoenix.  Is that cool, or too much edits?

Example for index test:

```
  # setup creates users for all tests, and generates the conn
  setup do
    {:ok, user1} = Accounts.create_user(@user1_attrs)
    {:ok, user2} = Accounts.create_user(@user2_attrs)
    conn = build_conn()
    # results are loaded into the context passed to each test
    {:ok, conn: conn, user1: user1, user2: user2}
  end

  test "index/2 responds with all Users", %{conn: conn, user1: user1, user2: user2} do

    response = conn
    |> get(user_path(conn, :index))
    |> json_response(200)

...
```

**Pull request merged**
