### PR TITLE
Update ex_doc

### PR DESCRIPTION
**Pull request by rodrigues**

### CODE REVIEW

**Comment by rodrigues** [comment]
EDIT: oh, it seems elixir requirements for ex_doc are too high, given phoenix supports older versions. Closing…

**Comment by wojtekmach** [comment]
I believe the patch is fine, both ExDoc v0.20.1 and v0.19.3 (that Phoenix master currently uses) require Elixir v1.7. Since dependency is defined as `{:ex_doc, ..., only: :docs}` it's OK if it uses different version than what Phoenix is targeting.

**Comment by rodrigues** [comment]
ok, reopening then @wojtekmach 👍

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
