### PR TITLE
use `~` in scss to resolve from node_modules

### PR DESCRIPTION
**Pull request by LostKobrakai**
See https://webpack.js.org/loaders/css-loader/#import for details

### CODE REVIEW

**Review by createdbypete — APPROVED** [review]

**Comment by cw789** [comment]
I like the notation, but for people not knowing webpack well it's not obvious anymore what's really happening...
And we'll make a file depending on webpack that probably don't need to know anything about webpack.

**Comment by LostKobrakai** [comment]
Even just the ˋ@importˋ working like it does is css-loader and therefore webpack behaviour. But I can see that it‘s less obvious.

**Comment by cw789** [comment]
Point with `@import`. Yes right.

**Comment by cw789** [comment]
Obsolete now as nprogress was replaced with topbar.
Thanks for learning me this neat feature.

**Pull request closed without merging**
