### PR TITLE
Fix broken links on testing_models.md

### PR DESCRIPTION
**Pull request by sirgallifrey**
Hello, I'm starting to learn Elixir/Phoenix and while reading the docs I found some broken links which this PR fixes. I used this commit 694800c02174ca6a1a0dbbdda2057014447c7885 as reference on how to fix Ecto Models Guide links

* Changed all references of `Ecto Models Guide` to `Ecto Guide`

* Changed all  `ecto_models.html` links to `ecto.html`

### CODE REVIEW

**Comment by sirgallifrey** [comment]
Also, should `Testing Models` be changed to `Testing Schemas`?

**Comment by jeregrine** [comment]
@sirgallifrey Thanks!! The testing guides need larger cleanup to work with contexts.

❤️

**Comment by jeregrine** [comment]
Also this is a duplicate of #2479 Thanks!!

**Comment by sirgallifrey** [comment]
Thanks @jeregrine ! Sorry for duplicating stuff, I'll try not to repeat this in the future :smile:

**Comment by jeregrine** [comment]
@sirgallifrey No worry! Its an easy mistake to make. Thank you for your contribution.

**Pull request closed without merging**
