### PR TITLE
Fix app config in namespaced umbrella apps

### PR DESCRIPTION
**Pull request by mikeover**
To address https://github.com/phoenixframework/phoenix/issues/3019

### CODE REVIEW

**Comment by chrismccord** [comment]
Thank you! Can you add a test-case? <3 <3 <3

**Comment by mikeover** [comment]
Sure, would you mind pointing me in the right direction? Where would this test belong?

**Comment by chrismccord** [comment]
https://github.com/phoenixframework/phoenix/blob/master/test/mix/tasks/phx.gen.html_test.exs#L271

**Comment by mikeover** [comment]
@chrismccord Added a test in the installer instead, please see https://github.com/phoenixframework/phoenix/pull/3031/commits/5bad464102ca75b283708caba96c0661edcade6a

**Comment by mikeover** [comment]
@chrismccord Rebased, has a test case, and ready to go.

**Comment by mikeover** [comment]
Thanks @chvanikoff - https://github.com/phoenixframework/phoenix/pull/3031/commits/5ed04e7605e194dbe1f0fb4f8ce2e62ac3816392 better?

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
