### PR TITLE
Envisage field of type map in phoenix.gen

### PR DESCRIPTION
**Pull request by shhavel**
#1908

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @shhavel. I am wondering if we should simply omit the map field. A text input into the data field is likely not the best way to handle a map field but on the other hand I like this approach because it shows at least *one* way of working with maps.

Thoughts?

**Comment by shhavel** [comment]
@josevalim I think it is good to point developers to a working example. Map field can also be omitted of course but then you should expect questions like "Why map field is omitted in generated views?".
I suggest to keep it - maybe later someone will come up with another idea and will refactor.

Thanks

**Comment by shhavel** [comment]
@josevalim 
As an alternative `textarea` can be generated for a map field in `phoenix.gen`.
Related required changes:
 - define protocol `Phoenix.HTML.Safe` for `Map` in `phoenix_html`
 - ability to cast JSON `String` into `Map` in `Ecto.Type`

If this is more appropriate solution I can do it.
Thanks

**Comment by josevalim** [comment]
I don't think implementing the HTML safe protocol for
Maps is the way to go. Most will rather traverse it by hand. So I
definitely prefer the current solution.


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Since the type does not integrate it with through all layers, we have decided it is best to add the map type by hand for now, thank you!

**Comment by MeerKatDev** [comment]
it's 2021, and no one seems to know how to handle that, still. is there any working example around?

**Comment by josevalim** [comment]
You can still add the field manually to your schema:

    field :my_field, :map

And similar in your migration.

The discussion here is mostly that, in order to fully automated, we need to include an approach to show and edit a map in the UI, and this is very specific to the purpose the map is being used.

**Pull request closed without merging**
