### PR TITLE
Spike default schemes and schemes config

### LINKED ISSUE #2998: Extensible schemes
Attempting to build a custom adapter for a new scheme (`coap`) on top of Phoenix master 1.4.0-dev.

This line hard codes the only scheme options as `http` and `https`:
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/supervisor.ex#L79

Is there a way to add other scheme/port mappings through configuration? I haven't be able to determine if it's possible reading the code.

Thanks!

### PR DESCRIPTION
**Pull request by tpitale**
Resolves #2998

### CODE REVIEW

**Comment by tpitale** [comment]
If you find this acceptable @chrismccord I can add docs as appropriate.

**Comment by tpitale** [comment]
Maybe an even better approach is a "registry" of adapters, mapped to their acceptable `scheme`s?

**Comment by tpitale** [comment]
Can't be 💯 sure, but that failure seems unrelated to this PR.

**Comment by josevalim** [comment]
Closed as outlined in #2998.

**Pull request closed without merging**
