### PR TITLE
Headers in sockets

### PR DESCRIPTION
**Pull request by mgwidmann**
### I'd like to start out by saying how great I think Phoenix is coming along! Great job! :+1: :tada: 

I know this is a painful topic, but I think it needs to be fleshed out if Phoenix is to succeed in the long run. The client-side HMAC token system cannot be the only method of authentication. I think it is an excellent feature though! There are currently, and will be more to come, use cases in which this system fails. First of all, not running the application over SSL immediately makes one time use token a vulnerability. Anyone who sniffs the token and makes the connection to the application first would gain credential access. Secondly, putting a security token on the client side accessible by javascript is a big time security violation by itself. If somehow you do get some kind injection issue (XSS or otherwise), now user tokens are available. This is the reason why session cookies are marked HTTP only and cannot be accessed by javascript. The web is already built this way for a reason.

In order to use the token system without a security hole, Phoenix must guarantee SSL and prevention of XSS or other injection issues (and even then I'm still uneasy about the architecture). Those are two tall orders to make, so heres what I propose. **Allow access to the session and headers in websocket connections!**

#### You may not like what I've done, thats ok if you prefer to reimplement it. But PLEASE consider adding this feature. Phoenix and its awesome web socket system are pretty much useless to me (and likely many others) without it.

> In case you are wondering what my use case is... 
> I have a Phoenix app here: https://github.com/mgwidmann/elixir-rails-websockets which will proxy to a locally configured (still TODO in the phoenix app) rails app so that I may lighten the web socket load on my rails server behind a reverse proxy like nginx. The Phoenix proxy needs to send over the session cookie to the rails app so that it appears transparently that the request came from the client (the rails session cookie most importantly needs to be sent, but other headers could be useful as well). The whole purpose of this is that I have a built rails application (which currently is better suited being built in rails than Phoenix IMO) which needs web socket support on a very limited set of hardware (which I feel MRI cannot handle since I won't be able to have more than a handful of workers). I didn't want to use JRuby or Rubinius as I have already built the app in MRI and it is too risky at this point to change. I will be deploying to production soon, either with my forked version of Phoenix or master, whichever supports this feature.

### CODE REVIEW

**Comment by josevalim** [comment]
Allowing session access in websockets is usually a no-go because websockets allow cross origin requests. Basically, using session authentication with websockets means a malicious website will be able to connect to your websocket with the user session and emit commands as the attacked user.

> In order to use the token system without a security hole, Phoenix must guarantee SSL and prevention of XSS or other injection issues (and even then I'm still uneasy about the architecture). Those are two tall orders to make

Those are requirements today for any website. If your website has any kind of authentication and it does not provide both SSL and XSS protection, it will be vulnerable, from top to bottom. This is not optional.

**Comment by mgwidmann** [comment]
In order for a cross origin request to access session data as you say would require the attacker to gain the session cookie which while not impossible is a generally accepted practice across the internet. Several other web socket systems allow access to the session, including faye in rails. 

All I'm stating is that Phoenix requires the user to implement their own security scheme, never a good plan. Users need to figure out a way of passing authentication information down to the client from a controller and back up to a web socket and keep it protected. Short answer, they will fail. Stick to the well established practices the internet has already created. If you plan on creating a new scheme as an experiment, make it optional and don't force it on others, if it is truly better others will realize it and begin using it.

**Comment by josevalim** [comment]
> In order for a cross origin request to access session data as you say would require the attacker to gain the session cookie.

That's not true for websockets. Websockets will include session/cookie data by default without needing the attacker to hijack it in any way:

http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by josevalim** [comment]
I agree we need to improve the current mechanisms, at least by making the tokens easy to generate, as well as maybe provide easy Origin validation, but accessing the cookie/session headers definitely isn't the way to go here.

**Comment by chrismccord** [comment]
> All I'm stating is that Phoenix requires the user to implement their own security scheme, never a good plan.

Agreed. We are planning to provide token generation/verification for you. In addition to the issues I've already load out about passing the conn in the socket on the ML, the other big issue is we abstract the transport layer. Most folks will just use the Router over http as their transport layer (which will have a %Plug.Conn{}), but what about a redis transport? A rabbitmq transport? All these don't have a `conn`, session, or headers, and all of these are possible today. You could build a Ruby channels client that publishes over redis and receives messages over redis instead of http. I understand the frustration since having this makes your life easier for your use-case, but can you simply encrypt the session on the rails end, and pass that up to the phoenix channel and decrypt with a shared key?

Rails side:
```ruby
def show
  @encrypted_session = Encryptor.encrypt(session, ENV["SOME_SHARED_KEY"])
  ...
end
```

```erb
<script>
   socket.join("foobar", {session:  "<%= @encrypted_session %>"}, function(chan){ ...
</script>
```

Phoenix Side:

```elixir
def join("foobar", %{"session" => encrypted_session}, socket) do
  case Encryptor.decrypt(encrypted_session, System.get_env("SOME_SHARED_KEY")) do
    {:ok, session} -> {:ok, assign(socket, :session, session)}
    _ -> :ignore
  end
end
```


Can this work for your use-case?

**Comment by mgwidmann** [comment]
I'm not sure how comfortable I feel about security tokens in javascript, even if they are only accessible to the phoenix.js socket. It just feels like theres too much room for error, and I doubt I'm alone in this.

According to the article that @josevalim posted, Phoenix should be checking the origin to match itself and closing the connection otherwise. That would alleviate this problem, would it not? It just seems absolutely ridiculous to me that the **server depends on the client** to give it information the server  already has. I feel this is the real issue of the current design.

@chrismccord Your point about a different transport is a legitimate one, though in those use cases I wouldn't expect the `conn` to be available. In those cases though, we are not authenticating a user, but a machine potentially acting on behalf of a user. As such, the token system in place is perfectly acceptable since it is reasonable to assume the machine properly authenticated the user. This is not the use case when accepting data from a client machine.

**Comment by josevalim** [comment]
> It just seems absolutely ridiculous to me that the server depends on the client to give it information the server already has.

That's not true. The server does not have this information. The client *always* need to pass it as part of the session, headers, an explicit token, etc. The only benefit of using a session is that it is managed for you on both client and server but with a huge downside that it is unsafe for websockets unless you add extra checks (and failing on those checks, you are vulnerable). We can, however, manage the current tokens automatically for you too and in a safer way. The code just isn't here yet.

So all in all, the only concern is that the current flow is not yet streamlined. We have already agreed with this and we are working on it. So *please wait* until we propose a solution. @chrismccord and I already gave plenty reasons for not relying on the session (security-wise) or on the connection (abstraction-wise).

Thank you.

**Comment by josevalim** [comment]
> @chrismccord Your point about a different transport is a legitimate one, though in those use cases I wouldn't expect the conn to be available. In those cases though, we are not authenticating a user, but a machine potentially acting on behalf of a user. As such, the token system in place is perfectly acceptable since it is reasonable to assume the machine properly authenticated the user. This is not the use case when accepting data from a client machine.

There are other transports besides a RabbitMQ or Redis. For example, we could have a custom TCP protocol for handling Android, iPhone and generally mobile requests. There is no connection and there is still a user behind.

**Comment by josevalim** [comment]
I have realized I haven't proposed any solution to your particular use case.

I would go with a simple Token Authentication mechanism (as in API Token authentication). On the Rails side, generate a token for the given user and store it in the database with the user id. On the Phoenix.Socket pass both the user_id and the token. On the Phoenix side, fetch the user_id and check if the tokens match.

This approach should be simple and safe as any other API Token authentication mechanism and should work cross applications.

**Comment by mgwidmann** [comment]
@josevalim While that may work, it introduces an additional dependency (the database, where it wasn't necessary prior) and I was hoping to make it a bit more generic than that (if this works I plan to use it on more applications). Additionally, it puts additional work on the rails app (where there was no additional work needed prior). After all, its just a proxy, why would it need a database connection? It should just echo whatever is sent to it...

I still see no reason why the headers, at the least, can't be accessible if they exist. If the connection technology doesn't allow headers, then I wouldn't expect them, but if it does then I do. Additional use cases such as geo location in web sockets become problematic. This is not the only use case, there will be tons more later on. **As much information as is available should be accessible, period**.

**Comment by josevalim** [comment]
If one is directly proxying the other, you can just include the token in the header when proxying. Then they are sync. I originally thought you would have nginx or apache proxying them.

**Comment by mgwidmann** [comment]
I think your original though was correct.

It works like this:
WS connections: client -> nginx -> phoenix -> rails
HTTP connections: client -> nginx -> rails

**Comment by josevalim** [comment]
So you can just forward all WS requests to Rails including the token validation and let Rails decide. You don't need the database, just generate and enforce the secret on Rails side. Search the message verifier here for examples: http://guides.rubyonrails.org/4_1_release_notes.html

**Comment by mgwidmann** [comment]
> That's not true. The server does not have this information. The client always need to pass it as part of the session, headers, an explicit token, etc.

Yes the browser always needs to pass it, but as I proved by my PR, the server does have this information because the browser does always pass it.

I'm not sure I agree, but its your decision. I don't believe hiding the information as `master` does currently is going to be appealing to new users. I want to pitch using Phoenix for some other things at my workplace, but with this issue I don't feel they'll go for it.

I'm going to keep my fork, sorry.

**Comment by josevalim** [comment]
Feel free to roll your own, just remember sessions are not safe without extra checks. We do plan to provide a streamlined workflow but this PR is not the direction we want to go. Hopefully you can drop your fork once we get there.

**Comment by mgwidmann** [comment]
Will do, thanks.

**Pull request closed without merging**
