### PR TITLE
Set application's module name as the default <title> in app layout.

### PR DESCRIPTION
**Pull request by utkarshkukreti**
I think this is better than defaulting to "Hello Phoenix!". Rails also does the same. What do you think?

### CODE REVIEW

**Comment by optikfluffel** [comment]
I'd like `<title>Hello <%= application_module %>!</title>` more.

**Comment by josevalim** [comment]
I like the "hello app module" suggested by Udo. :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
> I'd like <title>Hello <%= application_module %>!</title> more.

:+1: @utkarshkukreti can you update the PR? Thanks!

**Comment by utkarshkukreti** [comment]
Updated!

**Pull request merged**
