### PR TITLE
Minor improvements around controller

### PR DESCRIPTION
**Pull request by qcam**
Would it fit to use `Plug.Conn.put_private/3` in these cases?

### CODE REVIEW

**Comment by josevalim** [comment]
We don't do it to avoid setting the private and connection multiple times. We would need a better API in Plug to allow passing multiple keys at once.

**Comment by qcam** [comment]
Would it make sense use `Plug.Conn.merge_private/2`? https://hexdocs.pm/plug/Plug.Conn.html#merge_private/2

**Comment by josevalim** [comment]
Yes!!!! we need to check which Plug version it was added though and make sure the requirement is correct.

**Comment by qcam** [comment]
I think we introduced that in Plug 1.5.1 (https://github.com/elixir-plug/plug/blob/v1.6/CHANGELOG.md#v151-2018-05-17), while `master`  uses Plug `~> 1.10`. I guess we're good to use `merge_private` then?

**Comment by josevalim** [comment]
Yes!

**Pull request closed without merging**
