### PR TITLE
Fix markdown issues

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `markdownlint --ignore installer --ignore integration_test --disable MD004 MD007 MD013 M  D014 MD024 MD026 MD028 -- **/*.md`

See a detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

Not sure about the `instaler` folder and its usage, hence I ignored it from checking.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @kianmeng!

ExDoc recognizes `shell` but not `console`, and it uses the `$` to make the prompt recognizable but not selectable. So I would keep using `bash` instead of `console` and keep using the prompts. :)

**Comment by kianmeng** [comment]
> ExDoc recognizes `shell` but not `console`, and it uses the `$` to make the prompt recognizable but not selectable. So I would keep using `bash` instead of `console` and keep using the prompts. :)

ExDoc have supported the `console` name in shell lexer since v0.25.1? See
https://github.com/elixir-lang/ex_doc/commit/8b754f45160e65d38b4b792bded1c4893b3a892a

The reason for removing `$` from some code indent block without output, for example, the `README.md`, is when viewing these Markdown files from a browser in GitHub, the `$` is always selectable when we click the code indent block for copying. Either we've to manually remove the `$` after copying, or drag and select the command without `$`.

And to follow the [contribution guideline](https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md#guides):

> We use the "console" code fence for iex and shell commands.

Also, see https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output

**Comment by josevalim** [comment]
I will update the guides. :) I would like to keep `$`, because I think it is important context. :)

**Comment by josevalim** [comment]
And thanks for letting me know that `console` works, it is ok to migrate to it then. :)

**Comment by kianmeng** [comment]
@josevalim Done. I maintain the `$` prompt in those documents in `guides` folder, but remove it in `README.md`, so it matches with the instruction in `CONTRIBUTING.md`.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
