### PR TITLE
add ArgumentError if ets is not started

### PR DESCRIPTION
**Pull request by KazuCocoa**
How about raise an error if ets is not initialized ?

### CODE REVIEW

**Comment by chrismccord** [comment]
The solution would be to make sure ets is always started which I thought was default?

**Comment by KazuCocoa** [comment]
Yes, this PR is to check it. I read codes again, you are right.
hm.. I've been think this PR too much handling...

**Comment by chrismccord** [comment]
Thanks for the attempted fix! If you have a way to replicate your original issue, please open an issues with steps to reproduce and I'll see if something needs fixed. Thanks!

**Comment by KazuCocoa** [comment]
Thanks you :)

**Comment by josevalim** [comment]
No, let's add this. It can happen if you call something like `MyApp.Endpoint.url` without starting the endpoint.

**Comment by josevalim** [comment]
Actually, never mind. It would only happen if somehow you don't add phoenix to your supervision tree, which is the default.

**Pull request closed without merging**
