### PR TITLE
Add note to assert_broadcast documentation to prevent confusion

### PR DESCRIPTION
**Pull request by EskiMag**
Related to issue #3271

### CODE REVIEW

**Comment by EskiMag** [comment]
Any idea, why the check failed just on the `Elixir: 1.5 OTP Release: 20.3`?

**Comment by Gazler** [comment]
Don't worry about the test failure, I don't think it is related.

Could you please remove the `channel_test.exs` changes from this commit, it looks unrelated, perhaps you ran the formatter on it from your editor?

**Comment by EskiMag** [comment]
Sorry for the unintentional formatting. Now it's back to its original state. :-)

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
