### PR TITLE
Fire each event in a separate task for the LongPoll transport

### PR DESCRIPTION
**Pull request by hansihe**
Should fix https://github.com/phoenixframework/phoenix/issues/4323.

I originally intended to create a promise and resolving it immediately in order to run in a microtask instead of a macrotask, but that causes the same ordering issue, just one more level down (promises fired from promises).

A slightly more optimal approach here would be to fire the first event within the current task, and any subsequent ones from a `setInterval`. This might be advantageous if the lower bound timeout of `setTimeout` in some modern browsers end up creating problems, but that might cause even more ordering issues.

Added a commend, but I can remove that if the source code is an inappropriate location.

### CODE REVIEW

**Comment by hansihe** [comment]
Repro is located here: https://github.com/hansihe/phoenix_channel_microtask_repro/blob/main/assets/js/socket.js#L67-L83

With the WS transport, this produces `a b c d e`, while with the longpoll transport it produces a different order.

After this fix, both of them produce `a b c d e`.

**Comment by mcrumm** [comment]
Thanks @hansihe, nice work!

Per our conversation yesterday, if my understanding of the issue described in #4309 holds, then these timeouts are not at risk of being throttled because they are scheduled within a network response handler, so the additional `setTimeout` calls should have zero impact in that regard.

**Comment by hansihe** [comment]
Ahh, that makes sense, nice!

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
