### PR TITLE
Improve generated form styling.

### PR DESCRIPTION
**Pull request by scrogson**
Since we ship with bootstrap by default, let's use the markup and classes
to make things look a little nicer by default.

Alt text

### CODE REVIEW

**Comment by josevalim** [comment]
:+1:

**Comment by josevalim** [comment]
Can you please look into these things too and if we can change them due to bootstrap?

* The index table: https://github.com/phoenixframework/phoenix/blob/master/priv/templates/resource/index.html.eex#L3
* The flash messages in the layout: https://github.com/phoenixframework/phoenix/blob/master/priv/templates/new/web/templates/layout/application.html.eex#L23-L24
* And maybe some of those styles are no longer necessary: https://github.com/phoenixframework/phoenix/blob/master/priv/static/app.css#L31-L58

**Comment by scrogson** [comment]
@josevalim yes, will do.

**Comment by scrogson** [comment]
All set.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
