### PR TITLE
Expose code_change for channels. Fixes #1336

### LINKED ISSUE #1336: expose code_change for channels

### PR DESCRIPTION
**Pull request by stevedomin**
Proxy the Channel.Server code_change function to the overridable Channel
code_change callback.

### CODE REVIEW

**Comment by stevedomin** [comment]
@chrismccord this is a WIP, just wanted to check if that was going in the right direction.

I'm not sure which approach I should follow for testing this, would love some help on that.

**Comment by stevedomin** [comment]
Build is failing because of https://github.com/phoenixframework/phoenix/pull/1338

**Comment by chrismccord** [comment]
This is exactly what I had in mind. Nice work! I added tests, but I cheated by calling the code_change's directly, which suffices for me. I'll let @josevalim chime in if he things we need to test upgrading the running server. Thanks!

**Comment by igas** [comment]
@chrismccord @stevedomin thanks guys, it's exactly what I meant in slack.

**Pull request merged**
