### PR TITLE
Add Coverage Reports using Coveralls

### PR DESCRIPTION
**Pull request by optikfluffel**
For this to work you'd simply have to sign in at [Coveralls](https://coveralls.io) using your Github account and then activate this repo.
Oh and I also bumped the Elixir and OTP versions in `.travis.yml`.

### CODE REVIEW

**Comment by chrismccord** [comment]
Thanks, but last we checked shields.io was not a good api citizen. For example, it does no caching, and loading the home page makes like dozens of calls to the hex api alone.

**Comment by optikfluffel** [comment]
And if I change the badge url to the one from coveralls itself?

```markdown
[![Coverage Status](https://coveralls.io/repos/phoenixframework/phoenix/badge.svg?branch=coveralls&service=github)](https://coveralls.io/github/phoenixframework/phoenix?branch=coveralls)
````
[Coverage Status](https://coveralls.io/github/optikfluffel/phoenix?branch=coveralls)

Or don't you like coverage reporting?

**Comment by chrismccord** [comment]
It's not that I don't like it, it's just another thing to go wrong, a dependency to depend on, or have to maintain in the future, so I'm trying to limit things like that at the moment. I think code coverage reports are great fwiw.

**Comment by nickmerwin** [comment]
@chrismccord as the founder/maintainer of Coveralls I could help keep this integrated properly; it should be set-it-and-forget-it unless there are major changes to Elixir's coverage library.

You would also get automated coverage change status updates on PR's; I see there aren't many open right now, but in the future it may be handy.

Let me know if I can help, thanks! :+1:

**Comment by ericmj** [comment]
Another issue is that coverage tooling is not that great in Elixir at this point. It misses covering some lines which leads to weird code to make sure the line is covered. Also, code run at compile time is not covered at all so large parts of phoenix would never be covered.

**Pull request closed without merging**
