### PR TITLE
Add pool_count as an example for performance

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by rmoorman** [comment]
Just saw this issue, which reminded me of the fact that for a while now, I am using the database url query to set the poolsize `?pool_size=6`, following the documentation [here](https://hexdocs.pm/ecto/Ecto.Repo.html#module-urls). Wouldn't it make sense to document this here as well?

**Comment by josevalim** [comment]
I am not sure if pool_count would work there, if it does, please submit a pull request either adding support for it AND/OR documenting it?

**Comment by rmoorman** [comment]
@josevalim , it does work as documented in the linked ecto documentation page. I will make a new PR then.

**Pull request merged**
