### PR TITLE
Elaborate more about phoenix_controller_call doc

### PR DESCRIPTION
**Pull request by kpanic**
hi, this is a try to improve the documentation of `:phoenix_controller_call`
See issue https://github.com/phoenixframework/phoenix/issues/2712 for more context.

If you have better wording of the **NOTE** in this PR, please drop a comment.
Also please bear with me since I am not an English native speaker :)

If you think that it's too detailed this **NOTE**, then I will close the PR

Thanks!

### CODE REVIEW

**Comment by chrismccord** [comment]
Thanks for the PR! In this case I think the note is too specific since the issue you ran into was confusion on what is passed from the before call to the after call. In your case, you were passing a piece of the runtime metadata down to your after clause, which just happened to be a map with %Plug.Conn{} in it. If you'd like to take a 2nd pass, you can clarify the behavior in the `# Instrumentation` section, otherwise feel free to close. I appreciate the PR!

**Comment by kpanic** [comment]
Hey Chris,  thanks for the answer :) From my understanding the instrumenter for `phoenix_controller_call` is defined here https://github.com/phoenixframework/phoenix/blob/2d19cac62cdb54a59e85c08a68798e1b8714adbb/lib/phoenix/controller/pipeline.ex#L26

And `phoenix_controller_call` suggested to me that I would be able to hook into `:start` / `:stop` "events" and I would have the `conn` updated *after* the execution of `phoenix_controller_call(:start, ...)` -- so in `phoenix_controller_call(:stop, time_diff, data)` I would have the time difference of the whole controller execution and `data` which, in this case, I would expect that it would be an updated `conn` structure with the proper `conn.status`.

That was my first  interpretation. Would you please shed some light on this interpretation? That would help  me to refine the doc I think.

thanks for the patience :)

**Comment by chrismccord** [comment]
Where you are going wrong is the `:stop` callback receives the value you return from the `:start` callback, so it's entirely controller by your `:start` implementation.

**Comment by kpanic** [comment]
mmm but this `instrument` call is done at phoenix level. and it's phoenix that is passing the `conn` if I am not mistaken

**Comment by chrismccord** [comment]
to be clear, Phoenix passes the conn in the runtime metadata to your `:start` callbacks. What those callbacks return (your code), is passed to the `:stop` callbacks.

**Comment by kpanic** [comment]
yeah, this I understood, thank you.
I am just wondering if this makes sense (to not have an updated `conn`), from the functionality point of view, in those callbacks

**Comment by chrismccord** [comment]
The instrumenter doesn't pass the result of the code because it may raise and the exception is caught, so we can't guarantee `:stop` values should we try to pass them

**Pull request closed without merging**
