### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by gradenb**

### CODE REVIEW

**Comment by gradenb** [comment]
@chrismccord 
I'm browsing the code and looking for ways to start getting involved. It looks like there aren't many open issues. Is it worth investigating this failing spec?

**Comment by Gazler** [comment]
Thanks <3

**Comment by Gazler** [comment]
@gradenb If you find a way fix the intermittent test failures, that'd be awesome.

**Comment by gradenb** [comment]
@Gazler Any idea if there is a way to trigger the failures locally? Do they only seem to occur when running through Travis?

**Comment by Gazler** [comment]
Unfortunately there are a few intermittent failures, they are probably timing issues, so there is no easy way to trigger them. Here are the 4 most recent failures:

https://travis-ci.org/phoenixframework/phoenix/jobs/213260929#L265
https://travis-ci.org/phoenixframework/phoenix/jobs/213171731#L270
https://travis-ci.org/phoenixframework/phoenix/jobs/212736626#L270
https://travis-ci.org/phoenixframework/phoenix/jobs/212665663#L277

You will likely want to improve the robustness of these tests if possible.

**Pull request merged**
