### PR TITLE
Revert new template (rc1) mix.exs to working version

### LINKED ISSUE #2225: Possible mistake on Mix.exs default file from fresh rc1 install
Hi,

I just recently installed a **fresh** Phoenix 1.3.0-rc1 and was having a hard time deploying to Heroku.

### Deploy Error

**This is  `$ heroku logs --tail` output:**

```
2017-03-31T01:45:15.876452+00:00 app[api]: Release v14 created by user me@jonathansoifer.com
2017-03-31T01:44:31.000000+00:00 app[api]: Build succeeded
2017-03-31T01:45:21.350931+00:00 heroku[web.1]: Starting process with command `MIX_ENV=prod mix phx.server`
2017-03-31T01:45:23.798042+00:00 app[web.1]:     exited: {{shutdown,
2017-03-31T01:45:23.798041+00:00 app[web.1]:     application: customer_acquisition
2017-03-31T01:45:23.798015+00:00 app[web.1]:
2017-03-31T01:45:23.798040+00:00 app[web.1]: =INFO REPORT==== 31-Mar-2017::01:45:23 ===
2017-03-31T01:45:23.798042+00:00 app[web.1]:               {failed_to_start_child,
2017-03-31T01:45:23.798043+00:00 app[web.1]:                'Elixir.CustomerAcquisition.Web.Endpoint',
2017-03-31T01:45:23.798044+00:00 app[web.1]:                {shutdown,
2017-03-31T01:45:23.798051+00:00 app[web.1]:                 {failed_to_start_child,'Elixir.Phoenix.Endpoint.Handler',
2017-03-31T01:45:23.798052+00:00 app[web.1]:                  {shutdown,
2017-03-31T01:45:23.798053+00:00 app[web.1]:                    {ranch_listener_sup,
2017-03-31T01:45:23.798053+00:00 app[web.1]:                   {failed_to_start_child,
2017-03-31T01:45:23.798054+00:00 app[web.1]:                     'Elixir.CustomerAcquisition.Web.Endpoint.HTTP'},
2017-03-31T01:45:23.798054+00:00 app[web.1]:                    {'EXIT',
2017-03-31T01:45:23.798055+00:00 app[web.1]:                     {noproc,
2017-03-31T01:45:23.798056+00:00 app[web.1]:                      {gen_server,call,
2017-03-31T01:45:23.798057+00:00 app[web.1]:                        {set_new_listener_opts,
2017-03-31T01:45:23.798056+00:00 app[web.1]:                       [ranch_server,
2017-03-31T01:45:23.798058+00:00 app[web.1]:                         'Elixir.CustomerAcquisition.Web.Endpoint.HTTP',16384,
2017-03-31T01:45:23.798058+00:00 app[web.1]:                         [{env,
2017-03-31T01:45:23.798059+00:00 app[web.1]:                           [{dispatch,
2017-03-31T01:45:23.798060+00:00 app[web.1]:                             [{'_',[],
2017-03-31T01:45:23.798060+00:00 app[web.1]:                               [{[<<"socket">>,<<"websocket">>],
2017-03-31T01:45:23.798061+00:00 app[web.1]:                                 [],'Elixir.Phoenix.Endpoint.CowboyWebSocket',
2017-03-31T01:45:23.798062+00:00 app[web.1]:                                 {'Elixir.Phoenix.Transports.WebSocket',
2017-03-31T01:45:23.798062+00:00 app[web.1]:                                  {'Elixir.CustomerAcquisition.Web.Endpoint',
2017-03-31T01:45:23.798063+00:00 app[web.1]:                                   'Elixir.CustomerAcquisition.Web.UserSocket',
2017-03-31T01:45:23.798063+00:00 app[web.1]:                                   websocket}}},
2017-03-31T01:45:23.798064+00:00 app[web.1]:                                {'_',[],'Elixir.Plug.Adapters.Cowboy.Handler',
2017-03-31T01:45:23.798064+00:00 app[web.1]:                                 {'Elixir.CustomerAcquisition.Web.Endpoint',
2017-03-31T01:45:23.798065+00:00 app[web.1]:                                  []}}]}]}]}]}]}}}}}}}}},
2017-03-31T01:45:23.798066+00:00 app[web.1]:              {'Elixir.CustomerAcquisition.Application',start,[normal,[]]}}
2017-03-31T01:45:23.798066+00:00 app[web.1]:     type: permanent
2017-03-31T01:45:23.870799+00:00 app[web.1]: ** (exit) exited in: GenServer.call(Mix.State, {:get, {Map, :get, [:debug, false]}}, 5000)
2017-03-31T01:45:23.870801+00:00 app[web.1]:     ** (EXIT) no process
2017-03-31T01:45:23.870802+00:00 app[web.1]:     (elixir) lib/gen_server.ex:596: GenServer.call/3
2017-03-31T01:45:23.870803+00:00 app[web.1]:     (mix) lib/mix/cli.ex:65: Mix.CLI.run_task/2
2017-03-31T01:45:23.870804+00:00 app[web.1]:     (elixir) lib/code.ex:363: Code.require_file/2
2017-03-31T01:45:23.870804+00:00 app[web.1]:
2017-03-31T01:45:23.870999+00:00 app[web.1]: {"init terminating in do_boot",{noproc,{gen_server,call,[elixir_config,{get_and_put,at_exit,[]}]}}}
2017-03-31T01:45:23.871019+00:00 app[web.1]: init terminating in do_boot ()
2017-03-31T01:45:23.871288+00:00 app[web.1]:
2017-03-31T01:45:25.175329+00:00 app[web.1]: Crash dump is being written to: erl_crash.dump...done
2017-03-31T01:45:25.225434+00:00 heroku[web.1]: Process exited with status 1
2017-03-31T01:45:25.238818+00:00 heroku[web.1]: State changed from starting to crashed
2017-03-31T01:45:33.319992+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=liberty.ai request_id=2de26102-043c-4635-aee0-df1c0f812fd1 fwd="191.183.100.215,172.68.25.249" dyno= connect= service= status=503 bytes= protocol=http
2017-03-31T01:45:33.968974+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=liberty.ai request_id=f3f5e957-5796-4354-ade2-69bd7bc60c84 fwd="191.183.100.215,172.68.27.167" dyno= connect= service= status=503 bytes= protocol=http
```

### Expected behavior

This is the previous slice of code, in another repo **I migrated from rc0 to rc1**:

```
  def application do
    [mod: {Dotcom, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :runtime_tools]]
  end
```

### Actual behavior

This is my **problematic/fresh** app `mix.exs` file:

```
def application do
    [mod: {CustomerAcquisition.Application, []},
     extra_applications: [:logger, :runtime_tools]]
  end
```

*Apparently this was the original code from the fresh repo (rc1)*.

### PR DESCRIPTION
**Pull request by jaysoifer**
There was a "extra_applications" in `def application do` in Mix.exs but the core applications were missing.
Closes #2225

### CODE REVIEW

**Comment by josevalim** [comment]
Phoenix requires Elixir v1.4 and all you need there is extra_applications. It is an Elixir v1.4 feature.

**Comment by jaysoifer** [comment]
Ok, since Heroku doesn't support Elixir v1.4 right now (not sure how long this will take), would it make any sense to add some sort of warning to the rc1 docs?

**Comment by josevalim** [comment]
@jaysoifer Phoenix can be used with v1.3, the problem is that you copied an application generated for Elixir v1.4 and backported it. If you look closely, you will see that the generated application does include `elixir: "~> v1.4"` in the mix.exs.

**Comment by jaysoifer** [comment]
You're absolutely right. Thank you for the patience 😁

**Pull request closed without merging**
