### PR TITLE
Just updating the docs to render the raw function

### PR DESCRIPTION
**Pull request by bryansray**
Simple docs for render_existing to leverage the raw/1 function. Thanks to @chrismccord for the help.

### CODE REVIEW

**Comment by chrismccord** [comment]
Let's use `~E` so we don't show an example using `raw` ?

**Comment by josevalim** [comment]
@chrismccord oops, sorry. :)

**Comment by chrismccord** [comment]
No worries :) I recommended @bryansray submit a pr with `raw` earlier, but I just realized ~E would be better so we don't promote the use of raw as much as possible

**Comment by josevalim** [comment]
I agree. @bryansray would you be kind to send another PR that flips it to `~E`?

**Comment by bryansray** [comment]
@josevalim @chrismccord certainly. I'm not entirely sure I did this correctly, but there's a new PR using the sigil. Thanks, guys.

https://github.com/phoenixframework/phoenix/pull/1301

**Pull request merged**
