### PR TITLE
Bugfix: hours, minutes days out of order in forms

### PR DESCRIPTION
**Pull request by ijt**
The fix is to put them in a list instead of a map.

### CODE REVIEW

**Comment by josevalim** [comment]
@ijt good catch. Can we please add a simple test case too? We should just check two selects are not out of order. Which markup/select options were you getting before this change?

**Comment by ijt** [comment]
Sure, but it will take me some time since I have never written a test for Phoenix before. Without this change, the options are in whatever jumbled order they occur in the map.

**Comment by chrismccord** [comment]
Check out this test to get a good idea of what you'll need:
https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/html/form_test.exs

**Comment by ijt** [comment]
Okay, I ended up moving the datetime stuff out to a separate module called Phoenix.HTML.Form.Datetime so I could expose the hours, days etc. publicly for testing without making them part of the Form interface.

**Comment by josevalim** [comment]
The reason we should have a test through the form is because maps are ordered in the current OTP version. So we should always have 0, 1, 2, ...

However this is not going to be true in future releases, that's why the change is welcome. No worries though, I will investigate here.

**Comment by josevalim** [comment]
Merged locally, thank you!

**Pull request closed without merging**
