### PR TITLE
Babel 6 ES2015 compilation issue

### PR DESCRIPTION
**Pull request by matthewlehner**
This fixes an issue where the Phoenix JavaScript lib won't compile with Babel 6 and the ES2015 presets.

As of Babel 6.0, ES2015 transpiling has been moved to a preset plugin. Here's the the 6.0 [blog post](https://babeljs.io/blog/2015/10/29/6.0.0/) with some more details.

To reproduce,

```bash
npm i -g babel # to install Babel 6.0 and the `babel` binary
npm i babel-preset-es2015 # installs ES2015 preset (it isn't found when installed globally, must be local)

cd web/static/js
babel --presets "es2015" phoenix.js

TypeError: phoenix.js: Duplicate declaration "channel"
  482 |
  483 |   channel(topic, chanParams = {}){
> 484 |     let channel = new Channel(topic, chanParams, this)
      |         ^
  485 |     this.channels.push(channel)
  486 |     return channel
  487 |   }
    at File.buildCodeFrameError (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at Scope.checkBlockScopedCollisions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:428:27)
    at Scope.registerBinding (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:611:16)
    at Scope.registerDeclaration (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:515:14)
    at Object.BlockScoped (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:165:28)
    at Object.newFn (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:279:17)
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:151:16)

### CODE REVIEW

**Comment by chrismccord** [comment]
How is this a dup declaration? Scoping rules make that impossible. Is this a an es6 spec thing or arbitrary Babel decision?

**Comment by jjt** [comment]
It's a deliberate Babel opinion. Variable shadowing can cause confusion, especially in longer functions/blocks.

**Comment by chrismccord** [comment]
It's not shadowing since it's not on `this` scope, but alas JAVASCRIPPPPPPT

Thanks for saving me the headache of figuring this out when I upgraded.

**Comment by matthewlehner** [comment]
No problem! :smile:
There's an issue at babel/babel#2684, but if this is going to be default behaviour with Babel 6, this is probably the easiest path forward.

**Comment by chrismccord** [comment]
Agreed. Better to go with the flow here. Thanks again! :)

**Pull request merged**
