### PR TITLE
Update documentation on the http dispatch option

### PR DESCRIPTION
**Pull request by narrowtux**
* Added `.Web` to all the `MyApp` module names since phoenix 1.3 or later generates with that name
 * Added the needed route for the live_reload socket

### CODE REVIEW

**Comment by narrowtux** [comment]
Weirdly, a unit test failed (only in one elixir version) but this PR doesn't even change code

**Comment by chrismccord** [comment]
Can you update the alias to use `MyAppWeb` rather than the `.Web`? Also please kill the added whitespace on the newlines. Thanks!

**Comment by narrowtux** [comment]
Ok, I added the whitespace because the markdown parser produces this weirdness: 

image

I will change the module names though.

**Comment by narrowtux** [comment]
image
found another way to format the code blocks, now they render correctly

**Comment by narrowtux** [comment]
I also added a line about the init/1 callback in the endpoint module, which might help readers if they wonder why their changes to `config/*.exs` aren't applied (happened to me)

**Comment by narrowtux** [comment]
@chrismccord is there still something missing for this to be pulled?

**Comment by chrismccord** [comment]
❤️❤️❤️😍🔥

**Pull request merged**
