### PR TITLE
Do not connect automatically on `new Phoenix.Socket(..)`

### PR DESCRIPTION
**Pull request by scrogson**
```javascript
let socket = new Socket("/ws")
socket.connect()
...
```

### CODE REVIEW

**Comment by josevalim** [comment]
:+1:

**Comment by chrismccord** [comment]
@scrogson lets rename `close` to `disconnect` so we have parity with `connect()`. Also please doc the changelog

**Comment by scrogson** [comment]
So right now we are shipping with a minified version of `phoenix.js`. I think this may not be the route we want to take as it can cause issues in development and it's probably best to leave minification up to the user and their build tool? Would love to hear other thoughts.

I realize that this will be much better once we can extract `phoenix.js` into it's own bower/npm package. Would be nice to provide the original ES6 file, ES5 unminified and ES5 minified.

**Comment by ericmj** [comment]
:+1: on shipping with non-minified phoenix.js.

**Comment by scrogson** [comment]
Rebased on `master`

**Comment by chrismccord** [comment]
<3 <3 <3

**Pull request merged**
