### PR TITLE
Set port to PORT env var if it isn't set in config

### PR DESCRIPTION
**Pull request by guilleiguaran**
This set port to PORT env var if it isn't set in config

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! @guilleiguaran I think we should go with a specific value like `{:system, "PORT"}`. We would also need to change the endpoint/adapter.ex code to read from the environment too.

**Comment by guilleiguaran** [comment]
@josevalim so, If I understand fine the user should then define in the config:

```elixir
http: [port: {:system, "PORT"}]
```

Sounds good for me :+1:

**Comment by guilleiguaran** [comment]
@josevalim updated and now tests are green

**Comment by chrismccord** [comment]
Very nice. Thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
