### PR TITLE
feat: Add method offAll for Socket to remove all callback registrations

### PR DESCRIPTION
**Pull request by rnike**
Add a method for socket to remove all the callback registrations

usage
```js
socket.offAll();
```

### CODE REVIEW

**Comment by benjreinhart** [comment]
Curious, what is your use case for removing all callbacks?

If this functionality is accepted, wondering if it's nicer to use the existing `off` method with no arguments?

```js
// remove individual callback
socket.off(ref)

// remove everything
socket.off()
```

**Comment by rnike** [comment]
@benjreinhart To match our application's lifecycle, we are opening and closing the socket based on the user's interaction, when closing it we clean up the socket instance.

we are currently doing like this

```js
let socket = null;
let channel = null;
let refs = null;

function disconnect() {
  if (channel) {
    channel.disconnect();
    channel = null;
  }

  if (socket) {
    refs && socket.off(refs);
    socket.disconnect();
    socket = null;
    refs = null;
  }
}

function connect(channelName, token) {
  disconnect();

  socket = new Socket('url', {
    params: {
      token,
    },
  });

  refs = [
    socket.onMessage(() => {
      // ...
    }),
    socket.onOpen(() => {
      // ...
    }),
    socket.onError(() => {
      // ...
    }),
    socket.onClose(() => {
      // ...
    }),
  ];

  socket.connect();
  channel = socket.channel(channelName);
  channel.join();
}
```
I'm wondering if it is necessary to clean up before `socket.disconnect()`, is there any document about it?

**Comment by chrismccord** [comment]
Would it be better in our case then to instantiate a new socket instead of trying to clear out the old one?

**Comment by chrismccord** [comment]
I'm not convinced yet this is needed because you can rebuild the socket state as needed when you want to teardown and reup the connection. You can also write a simple wrapper that collects the refs yourself and calls off. Thanks!

**Pull request closed without merging**
