### PR TITLE
fix flash function selector

### PR DESCRIPTION
**Pull request by jamilabreu**
currently throws an "invalid selector" error:

https://share.cleanshot.com/qySqJgHs

### CODE REVIEW

**Comment by Gazler** [comment]
I could be wrong, but I believe the existing code is correct and the error here is because you are missing an id? The `hide/2` function takes a selector, which is being called with "#" in this instance.

**Comment by Gazler** [comment]
That being said, looking at the code, if an ID is nil, one is automatically assigned for the element based on the kind:

```
      id={@id || "flash-#{@kind}"}
      phx-click={JS.push("lv:clear-flash", value: %{key: @kind}) |> hide("#{@id}")}
 ```
 
 So perhaps the fix is actually to do:
 
 ```
       id={@id || "flash-#{@kind}"}
      phx-click={JS.push("lv:clear-flash", value: %{key: @kind}) |> hide("#" <> @id || "flash-#{@kind}")}
```

**Comment by josevalim** [comment]
Maybe we should remove the `default` from :id and use `assign_new` to set it if none is set? Can you please verify and amend @jamilabreu?

**Comment by josevalim** [comment]
Close in favor of #5542.

**Pull request closed without merging**
