### PR TITLE
Use put_req_header correctly in recycle documentation

### PR DESCRIPTION
**Pull request by radar**
The first arg for `put_req_header` should be the `conn` itself.

### CODE REVIEW

**Comment by Gazler** [comment]
Good spot. Perhaphs the code should assign the result back to `conn` to reflect the other sample lower down.

Could you change `recycle` to `recycle()` so that @whatyouhide doesn't come in and change it after please? :)

**Comment by josevalim** [comment]
@Gazler we will only warn if a variable becomes a function call, in this case it can't happen, so we are fine (that's a common misconception :D).

**Comment by Gazler** [comment]
@josevalim Thanks for clarifying. @radar Sorry for the misinformation!

**Comment by radar** [comment]
All good! 👍👍

**Comment by chrismccord** [comment]
I actually would prefer if we changed the null-amity call to `recycle()`. Please make that change then we are all set. Thanks!

**Comment by radar** [comment]
Done :)

**Comment by Gazler** [comment]
Thanks <3

**Pull request merged**
