### PR TITLE
Add `c:Phoenix.Endpoint.server_info/1`

### PR DESCRIPTION
**Pull request by mtrudel**
Solves https://github.com/phoenixframework/phoenix/pull/5553

Paired with https://github.com/mtrudel/bandit/pull/258 over in Bandit-land

@mtrudel will follow with a change to refactor https://github.com/livebook-dev/livebook/pull/2316 once this is merged/released (@josevalim relevant to your recent interests)

### CODE REVIEW

**Comment by josevalim** [comment]
Thank @mtrudel. I am thinking this should be a single function, called `server_info(:http | :https)`. WDYT?

**Comment by josevalim** [comment]
Perhaps it should be `server_info(:http | :https) :: {:ok, address, port} | {:local, path} | {:error, reason}`

**Comment by mtrudel** [comment]
> I am thinking this should be a single function, called server_info(:http | :https)

Yep; I'll work that up; won't take a few minutes.

**Comment by mtrudel** [comment]
Revised and ready to go!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
