### PR TITLE
fix react native crash

### PR DESCRIPTION
**Pull request by G3z**
globalwindow exists in react native but it doesn't have the addEventListener method
i didn't research why the object exists nor what it is exactly

### CODE REVIEW

**Comment by chrismccord** [comment]
Can you rename `globalWindow` to `phxWindow` ? Thanks!

**Comment by G3z** [comment]
done ;)

**Comment by scmx** [comment]
Cool, I ran into this as well. 
It solved the issue for me

react-native-phoenix-socket-error

**Comment by nazmifeeroz** [comment]
@scmx 
i tried changing the package.json. i still have the same error. can you elaborate more on fixing this?

**Comment by nazmifeeroz** [comment]
i fixed this by importing the file path itself.
```
import {Socket as PhoenixSocket} from '../../node_modules/phoenix/assets/js/phoenix'
```

somehow even after patching with above, the app does not update to the latest edit.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by pbrandone** [comment]
was this release published to npm?
Latest available there is 1.4.3: https://www.npmjs.com/package/phoenix

**Pull request merged**
