### PR TITLE
Escape plug options in helpers

### LINKED ISSUE #3554: You cannot pass 3-ary tuple as a plug configuration
### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

  Elixir 1.9.1 (compiled with Erlang/OTP 22)
  ```

* Phoenix version (mix deps):
  ```
  * telemetry 0.4.0 (Hex package) (rebar3)
    locked at 0.4.0 (telemetry) 8339bee3
    ok
  * phoenix_pubsub 1.1.2 (Hex package) (mix)
    locked at 1.1.2 (phoenix_pubsub) 496c303b
    ok
  * mime 1.3.1 (Hex package) (mix)
    locked at 1.3.1 (mime) 30ce04ab
    ok
  * plug_crypto 1.0.0 (Hex package) (mix)
    locked at 1.0.0 (plug_crypto) 18e49317
    ok
  * plug 1.8.3 (Hex package) (mix)
    locked at 1.8.3 (plug) 12d5f979
    ok
  * phoenix 1.4.10 (Hex package) (mix)
    locked at 1.4.10 (phoenix) 619e4a54
    ok
  ```
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: `Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin`

### Expected behavior

This should compile:

```elixir
defmodule PhxBugExample do
  use Phoenix.Router

  defmodule SubPlug do
    def init(args), do: Map.new(args)

    def call(conn, args) do
      IO.inspect(args)

      conn
    end
  end

  get "/foo", SubPlug, func: {M, :f, [10]}
end
```

### Actual behavior

Above code do not compile due to macro escaping errors:

```
Compiling 1 file (.ex)

== Compilation error in file lib/phx_bug_example.ex ==
** (CompileError) lib/phx_bug_example.ex: invalid quoted expression: {M, :f, '\n'}

Please make sure your quoted expressions are made of valid AST nodes. If you would like to introduce a value into the AST, such as a four-element tuple or a map, make sure to call Macro.escape/1 before
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    expanding macro: Phoenix.Router.__before_compile__/1
```

### PR DESCRIPTION
**Pull request by sionide21**
Fixes #3554

I wasn't sure where to put tests for something like this. If someone can point me in the right direction, I'll be glad to go back and add some.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @sionide21! For testing, you can define a route in `helpers_test.exs` that crashes compilation and have a simple test that ensures the route can be generated properly. If you have further questions, please ask!

**Comment by sionide21** [comment]
Thanks @josevalim! I've added a test and verified that it fails against master.

**Comment by sionide21** [comment]
This test failure doesn't look related... Could you restart the build and see if still fails?

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
